// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package port

import (
	"github.com/rafaelgfirmino/dev_to/using_tilt/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserDbRepository creates a new instance of MockUserDbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDbRepository {
	mock := &MockUserDbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserDbRepository is an autogenerated mock type for the UserDbRepository type
type MockUserDbRepository struct {
	mock.Mock
}

type MockUserDbRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDbRepository) EXPECT() *MockUserDbRepository_Expecter {
	return &MockUserDbRepository_Expecter{mock: &_m.Mock}
}

// FindUserByEmail provides a mock function for the type MockUserDbRepository
func (_mock *MockUserDbRepository) FindUserByEmail(email string) (*domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDbRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockUserDbRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email
func (_e *MockUserDbRepository_Expecter) FindUserByEmail(email interface{}) *MockUserDbRepository_FindUserByEmail_Call {
	return &MockUserDbRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", email)}
}

func (_c *MockUserDbRepository_FindUserByEmail_Call) Run(run func(email string)) *MockUserDbRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserDbRepository_FindUserByEmail_Call) Return(user *domain.User, err error) *MockUserDbRepository_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserDbRepository_FindUserByEmail_Call) RunAndReturn(run func(email string) (*domain.User, error)) *MockUserDbRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserById provides a mock function for the type MockUserDbRepository
func (_mock *MockUserDbRepository) FindUserById(id string) (*domain.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserById")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDbRepository_FindUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserById'
type MockUserDbRepository_FindUserById_Call struct {
	*mock.Call
}

// FindUserById is a helper method to define mock.On call
//   - id
func (_e *MockUserDbRepository_Expecter) FindUserById(id interface{}) *MockUserDbRepository_FindUserById_Call {
	return &MockUserDbRepository_FindUserById_Call{Call: _e.mock.On("FindUserById", id)}
}

func (_c *MockUserDbRepository_FindUserById_Call) Run(run func(id string)) *MockUserDbRepository_FindUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserDbRepository_FindUserById_Call) Return(user *domain.User, err error) *MockUserDbRepository_FindUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserDbRepository_FindUserById_Call) RunAndReturn(run func(id string) (*domain.User, error)) *MockUserDbRepository_FindUserById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetUserByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByEmail(email string) (*domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - email
func (_e *MockUserRepository_Expecter) GetUserByEmail(email interface{}) *MockUserRepository_GetUserByEmail_Call {
	return &MockUserRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", email)}
}

func (_c *MockUserRepository_GetUserByEmail_Call) Run(run func(email string)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) Return(user *domain.User, err error) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) RunAndReturn(run func(email string) (*domain.User, error)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserById(id string) (*domain.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockUserRepository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - id
func (_e *MockUserRepository_Expecter) GetUserById(id interface{}) *MockUserRepository_GetUserById_Call {
	return &MockUserRepository_GetUserById_Call{Call: _e.mock.On("GetUserById", id)}
}

func (_c *MockUserRepository_GetUserById_Call) Run(run func(id string)) *MockUserRepository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserById_Call) Return(user *domain.User, err error) *MockUserRepository_GetUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserById_Call) RunAndReturn(run func(id string) (*domain.User, error)) *MockUserRepository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}
